services:
  postgres:
    image: postgres:16-alpine
    container_name: turnow-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: QUETEimporta1505
      POSTGRES_INITDB_ARGS: "-c client_encoding=UTF8"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/01-init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
